### ISSUE TITLE
Forward issue

### ISSUE THREAD

**Issue by djannot** [mrwilson/helixdns#14]
Hi,

Here is the issue I have as soon as I try to resolve a DNS name not in etcd:
2015/01/18 15:15:10 Starting servers...
2015/01/18 15:15:10 Setting up watch to validate entries
2015/01/18 15:15:19 Could not get record for win2008r2vc.ad.forest., forwarding to 10.64.231.29
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x46697f]

goroutine 18 [running]:
github.com/miekg/dns.(*Msg).PackBuffer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/miekg/dns/msg.go:1471 +0x8f
github.com/miekg/dns.(*Msg).Pack(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/miekg/dns/msg.go:1463 +0x71
github.com/miekg/dns.(*response).WriteMsg(0xc20802e240, 0x0, 0x0, 0x0)
	/go/src/github.com/miekg/dns/server.go:567 +0x252
main.HelixServer.Handler(0x35, 0x7f014e008f78, 0xc20801e440, 0x7f014e008fb0, 0xc20802a9f0, 0x7f014e00b4c8, 0xc20802e240, 0xc2080642d0)

Then, I need to restart helixdns

Thanks

**Comment by djannot** [comment]
Found that it was because I had to add the port in the forward option.
I would suggest to update the command line help ;-)
